### PR TITLE
[FEATURE] Add admin

### PR DESCRIPTION
**Pull request by sentientwaffle**
Requires https://github.com/interledger/five-bells-ledger/pull/48, https://github.com/interledger/five-bells-trader/pull/43, https://github.com/interledger/five-bells-visualization/pull/22

### CODE REVIEW

**Comment by sentientwaffle** [comment]
Don't merge yet; this is broken.

**Comment by emschwartz** [comment]
@sentientwaffle What's the status of this? Should we close it?

**Comment by sentientwaffle** [comment]
No need to close, I think the issue will be fixed by the `/connectors` endpoint: https://github.com/interledger/five-bells-ledger/commit/d1d263cd10fc67f12d25ddb73a281858fed34e85.

**Comment by emschwartz** [comment]
LGTM

**Pull request merged**
